module.exports = {
    'indent-style': 'nonmixed',
    'indent-num-spaces': 4,
    'spec-char-escape': true,
    'tag-self-close': false,
    'disallowed-tags': ['style', 'b', 'i'],
    'disable-inline-style': true,
    'doctype-first': true,
    'doctype-html5': true,
    'attr-name-style': 'lowercase',
    'attr-no-duplication': true,
    'attr-no-unsafe-chars': true,
    'attr-value-quotes': 'double',
    'attr-value-not-empty': true,
    'id-unique': true,
    'id-class-ad-disabled': true,
    'id-class-value': 'underscore',
    'alt-require': true,
    'img-src-not-empty': true,
    'href-type': false,
    'csslint': false,
    'tag-self-close': false,
    'label-for': true
};
