module.exports = {
    'indent-style': false,
    'indent-num-spaces': false,
    'spec-char-escape': false,
    'tag-self-close': false,
    'disallowed-tags': false,
    'disable-inline-style': false,
    'doctype-first': false,
    'doctype-html5': false,
    'attr-name-style': false,
    'attr-no-duplication': false,
    'attr-no-unsafe-chars': false,
    'attr-value-quotes': false,
    'attr-value-not-empty': false,
    'id-unique': false,
    'id-class-ad-disabled': false,
    'id-class-value': false,
    'alt-require': false,
    'img-src-not-empty': false,
    'href-type': false,
    'csslint': false,
    'tag-self-close': false,
    'label-for': false
};
