module.exports = {
    'attr-bans': ['style'],
    'indent-style': 'nonmixed',
    'indent-width': 4,
    'text-escape-spec-char': true,
    'tag-self-close': false,
    'tag-bans': ['style', 'b', 'i'],
    'tag-name-lowercase': true,
    'doctype-first': false,
    'doctype-html5': false,
    'attr-name-style': 'lowercase',
    'attr-no-dup': true,
    'attr-no-unsafe-chars': true,
    'attr-quote-style': 'double',
    'attr-req-value': true,
    'id-no-dup': true,
    'id-class-no-ad': true,
    'id-class-style': 'underscore',
    'img-req-alt': true,
    'img-req-src': true,
    'href-style': false,
    'csslint': false,
    'label-req-for': true,
    'line-end-style': 'lf'
};
