module.exports = {
    'attr-bans': false,
    'indent-style': false,
    'indent-width': false,
    'text-escape-spec-char': false,
    'tag-self-close': false,
    'tag-bans': false,
    'doctype-first': false,
    'doctype-html5': false,
    'attr-name-style': false,
    'attr-no-dup': false,
    'attr-no-unsafe-chars': false,
    'attr-quote-style': false,
    'attr-req-value': false,
    'id-no-dup': false,
    'id-class-no-ad': false,
    'id-class-style': false,
    'id-class-ignore-regex': false,
    'img-req-alt': false,
    'img-req-src': false,
    'href-style': false,
    'csslint': false,
    'label-req-for': false,
    'line-end-style': false,
    'head-req-title': false,
    'title-no-dup': false,
    'title-max-length': false
};
